export const APPOINTMENT_CREATE_REQUEST = 'APPOINTMENT_CREATE_REQUEST'
export const APPOINTMENT_CREATE_SUCCESS = 'APPOINTMENT_CREATE_SUCCESS'
export const APPOINTMENT_CREATE_FAIL = 'APPOINTMENT_CREATE_FAIL'

export const APPOINTMENT_LIST_REQUEST = 'APPOINTMENT_LIST_REQUEST'
export const APPOINTMENT_LIST_SUCCESS = 'APPOINTMENT_LIST_SUCCESS'
export const APPOINTMENT_LIST_FAIL = 'APPOINTMENT_LIST_FAIL'
export const APPOINTMENT_LIST_RESET = 'APPOINTMENT_LIST_RESET'

export const APPOINTMENT_DELETE_REQUEST = 'APPOINTMENT_DELETE_REQUEST'
export const APPOINTMENT_DELETE_SUCCESS = 'APPOINTMENT_DELETE_SUCCESS'
export const APPOINTMENT_DELETE_FAIL = 'APPOINTMENT_DELETE_FAIL'


